mk/cc.mk: make implicit function declarations fatal
When building openrc from git on uclibg-ng system
a lot of warnings suggest prototypes are missing
for various functions:

```
  start-stop-daemon.c:1197:21: warning: implicit declaration of function 'initgroups' [-Wimplicit-function-declaration]
   if (changeuser && initgroups(changeuser, gid))
                     ^
  start-stop-daemon.c:1197:3: warning: nested extern declaration of 'initgroups' [-Wnested-externs]
   if (changeuser && initgroups(changeuser, gid))
   ^
```

It means all arguments are defaulted to 'int'. It's a
problem for pointer arguments where truncation happens.

To avoid that truncation change forbids inplicit declarations.

Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>